// Catálogo do Nocautecel: só o que foi lido na ficha oficial de cada fabricante.
// null = não consta na ficha / não verificado. O site mostra isso, não completa.
// Medidas em mm; dobráveis usam as medidas DOBRADO (é o que vai ao bolso).
// zoom = zoom óptico declarado; "qualidade óptica" (recorte do sensor) não conta.
// bateria = mAh declarado; a Apple não declara mAh, só horas de vídeo (batNota).
// loja: "google" (Play Store), "apple" (App Store), false (sem Play Store), null (não verificado).
window.CATALOGO = {
  edge:{nome:"Galaxy S25 Edge", curto:"S25 Edge", marca:"Samsung", sigla:"EDGE",
    alt:158.2, larg:75.6, esp:5.8, peso:163, tela:'6,7"', bateria:3900, batNota:null, cam:200,
    zoom:0, zoomTxt:"sem teleobjetiva · 2x por recorte", g5:true, loja:"google", seg:null, dobra:null,
    foto:{w:245, h:326, autor:"Miyako Fujimiya", lic:"CC BY-SA 4.0", arquivo:"Samsung_Galaxy_S25_Edge_(2).jpg", alt:"Traseira do Galaxy S25 Edge, prata."},
    fonte:{url:"https://www.samsung.com/br/smartphones/galaxy-s25-edge/specs/", acesso:"11/09/2026"}},
  pura:{nome:"Huawei Pura 80 Pro", curto:"Pura 80 Pro", marca:"Huawei", sigla:"PURA",
    alt:163.0, larg:76.1, esp:8.3, peso:219, tela:'6,8"', bateria:5170, batNota:"nominal", cam:50,
    zoom:4, zoomTxt:"4x óptico", g5:false, loja:false, seg:null, dobra:null,
    foto:{w:600, h:800, autor:"Leongyy02", lic:"CC BY-SA 4.0", arquivo:"Huawei_Pura_80_Pro_Glazed_Red.jpg", alt:"Traseira do Huawei Pura 80 Pro, vermelho.", nota:"foto da versão vermelha; o link vai para a preta"},
    fonte:{url:"https://consumer.huawei.com/br/phones/pura80-pro/specs/", acesso:"11/09/2026"}},
  ultra:{nome:"Galaxy S26 Ultra 256 GB", curto:"S26 Ultra", marca:"Samsung", sigla:"ULTRA",
    alt:163.6, larg:78.1, esp:7.9, peso:214, tela:'6,9"', bateria:5000, batNota:"típica · nominal 4.855", cam:200,
    zoom:5, zoomTxt:"3x e 5x ópticos", g5:true, loja:"google", seg:"2033-02-28", dobra:null,
    foto:{arquivoLocal:"ultra", w:600, h:800, autor:"Kyu3a", lic:"CC BY-SA 4.0", arquivo:"Galaxy_S26_Ultra_-_2.jpg", alt:"Traseira do Galaxy S26 Ultra, roxo."},
    fonte:{url:"https://www.samsung.com/br/smartphones/galaxy-s26-ultra/specs/", acesso:"11/09/2026"}},
  s26u1t:{nome:"Galaxy S26 Ultra 1 TB", curto:"S26 Ultra 1 TB", marca:"Samsung", sigla:"ULTRA",
    alt:163.6, larg:78.1, esp:7.9, peso:214, tela:'6,9"', bateria:5000, batNota:"típica · nominal 4.855", cam:200,
    zoom:5, zoomTxt:"3x e 5x ópticos", g5:true, loja:"google", seg:"2033-02-28", dobra:null,
    foto:{arquivoLocal:"ultra", w:600, h:800, autor:"Kyu3a", lic:"CC BY-SA 4.0", arquivo:"Galaxy_S26_Ultra_-_2.jpg", alt:"Traseira do Galaxy S26 Ultra, roxo."},
    fonte:{url:"https://www.samsung.com/br/smartphones/galaxy-s26-ultra/specs/", acesso:"11/09/2026"}},
  matext:{nome:"Huawei Mate XT Ultimate Design", curto:"Mate XT", marca:"Huawei", sigla:"XT",
    alt:156.7, larg:73.5, esp:12.8, peso:298, tela:'6,4" fechado · 10,2" aberto', bateria:5600, batNota:"típica · nominal 5.500", cam:50,
    zoom:5.5, zoomTxt:"5,5x óptico (periscópio)", g5:null, loja:false, seg:null, dobra:"dobra em três; 219,0 mm de largura aberto",
    foto:{w:600, h:800, autor:"メイド理世", lic:"CC BY-SA 4.0", arquivo:"Huawei_Mate_XT_Ultimate_Design.jpg", alt:"Huawei Mate XT dobrado em zigue-zague numa vitrine."},
    fonte:{url:"https://consumer.huawei.com/en/phones/mate-xt-ultimate-design/specs/", acesso:"12/09/2026"}},
  ip17pm:{nome:"iPhone 17 Pro Max", curto:"17 Pro Max", marca:"Apple", sigla:"PRO MAX",
    alt:163.4, larg:78.0, esp:8.75, peso:231, tela:'6,9"', bateria:null, batNota:"Apple não declara mAh · até 37 h de vídeo", cam:48,
    zoom:4, zoomTxt:"4x óptico · 8x com qualidade óptica", g5:true, loja:"apple", seg:null, dobra:null,
    foto:{w:600, h:800, autor:"Ahmad Ali Karim", lic:"CC0", arquivo:"Deep_Blue_iPhone_17_Pro_Max.jpg", alt:"Traseira do iPhone 17 Pro Max, azul."},
    fonte:{url:"https://support.apple.com/pt-br/125091", acesso:"12/09/2026"}},
  ip17p:{nome:"iPhone 17 Pro", curto:"17 Pro", marca:"Apple", sigla:"17 PRO",
    alt:150.0, larg:71.9, esp:8.75, peso:204, tela:'6,3"', bateria:null, batNota:"Apple não declara mAh · até 31 h de vídeo", cam:48,
    zoom:4, zoomTxt:"4x óptico · 8x com qualidade óptica", g5:true, loja:"apple", seg:null, dobra:null,
    foto:{w:600, h:800, autor:"Olgierd Rudak", lic:"CC0", arquivo:"IPhone_17_Pro_(2025-12-28).jpg", alt:"Traseira do iPhone 17 Pro, prata, sobre madeira."},
    fonte:{url:"https://support.apple.com/pt-br/125090", acesso:"12/09/2026"}},
  ip16pm:{nome:"iPhone 16 Pro Max", curto:"16 Pro Max", marca:"Apple", sigla:"PRO MAX",
    alt:163.0, larg:77.6, esp:8.25, peso:227, tela:'6,9"', bateria:null, batNota:"Apple não declara mAh · até 33 h de vídeo", cam:48,
    zoom:5, zoomTxt:"5x óptico", g5:true, loja:"apple", seg:null, dobra:null,
    foto:{w:600, h:800, autor:"メイド理世", lic:"CC BY-SA 4.0", arquivo:"Back_view_of_iPhone_16_Pro_Max_Natural_Titanium.jpg", alt:"Traseira do iPhone 16 Pro Max na mão."},
    fonte:{url:"https://support.apple.com/pt-br/121032", acesso:"12/09/2026"}},
  ip16p:{nome:"iPhone 16 Pro", curto:"16 Pro", marca:"Apple", sigla:"16 PRO",
    alt:149.6, larg:71.5, esp:8.25, peso:199, tela:'6,3"', bateria:null, batNota:"Apple não declara mAh · até 27 h de vídeo", cam:48,
    zoom:5, zoomTxt:"5x óptico", g5:true, loja:"apple", seg:null, dobra:null, foto:null,
    fonte:{url:"https://support.apple.com/pt-br/121031", acesso:"12/09/2026"}},
  ip16plus:{nome:"iPhone 16 Plus", curto:"16 Plus", marca:"Apple", sigla:"PLUS",
    alt:160.9, larg:77.8, esp:7.8, peso:199, tela:'6,7"', bateria:null, batNota:"Apple não declara mAh · até 27 h de vídeo", cam:48,
    zoom:2, zoomTxt:'2x ("zoom in óptico", segundo a Apple)', g5:true, loja:"apple", seg:null, dobra:null,
    foto:{w:600, h:800, autor:"メイド理世", lic:"CC BY-SA 4.0", arquivo:"Back_view_of_iPhone_16_Plus_Black.jpg", alt:"Traseira do iPhone 16 Plus preto na mão."},
    fonte:{url:"https://support.apple.com/pt-br/121030", acesso:"12/09/2026"}},
  ip13pm:{nome:"iPhone 13 Pro Max", curto:"13 Pro Max", marca:"Apple", sigla:"13",
    alt:160.8, larg:78.1, esp:7.65, peso:238, tela:'6,7"', bateria:null, batNota:"Apple não declara mAh · até 28 h de vídeo", cam:12,
    zoom:3, zoomTxt:"3x óptico", g5:true, loja:"apple", seg:null, dobra:null, foto:null,
    fonte:{url:"https://support.apple.com/pt-br/111870", acesso:"12/09/2026"}},
  fold8u:{nome:"Galaxy Z Fold8 Ultra", curto:"Z Fold8 Ultra", marca:"Samsung", sigla:"FOLD",
    alt:158.4, larg:72.8, esp:8.9, peso:215, tela:'6,5" fechado · 8,0" aberto', bateria:5000, batNota:"típica · nominal 4.854", cam:200,
    zoom:3, zoomTxt:"3x óptico", g5:true, loja:"google", seg:"2033-07-31", dobra:"aberto: 158,4 × 143,2 × 4,1 mm", foto:null,
    fonte:{url:"https://www.samsung.com/br/smartphones/galaxy-z-fold8-ultra/specs/", acesso:"12/09/2026"}},
  flip8:{nome:"Galaxy Z Flip8", curto:"Z Flip8", marca:"Samsung", sigla:"FLIP",
    alt:85.7, larg:75.4, esp:13.1, peso:180, tela:'4,1" fechado · 6,9" aberto', bateria:4300, batNota:"típica · nominal 4.174", cam:50,
    zoom:0, zoomTxt:"sem teleobjetiva · 2x com qualidade óptica", g5:true, loja:"google", seg:"2033-07-31", dobra:"aberto: 166,9 × 75,4 × 6,1 mm",
    foto:{w:600, h:800, autor:"Kyu3a", lic:"CC BY-SA 4.0", arquivo:"Galaxy_Z_Flip8_-_2.jpg", alt:"Galaxy Z Flip8 rosa, fechado, na mão."},
    fonte:{url:"https://www.samsung.com/br/smartphones/galaxy-z-flip8/specs/", acesso:"12/09/2026"}},
  razr70u:{nome:"Motorola Razr 70 Ultra", curto:"Razr 70 Ultra", marca:"Motorola", sigla:"RAZR",
    alt:88.12, larg:73.99, esp:15.69, peso:199, tela:'4,0" fechado · 6,96" aberto', bateria:5000, batNota:null, cam:50,
    zoom:null, zoomTxt:"zoom óptico não consta na ficha", g5:true, loja:"google", seg:null, dobra:"aberto: 171,48 × 73,99 × 7,19 mm", foto:null,
    fonte:{url:"https://www.motorola.com.br/smartphone-motorola-razr-70-ultra-5g/p", acesso:"12/09/2026"}},
  oppox9p:{nome:"OPPO Find X9 Pro", curto:"Find X9 Pro", marca:"OPPO", sigla:"X9",
    alt:161.26, larg:76.46, esp:8.25, peso:224, tela:'6,78"', bateria:7500, batNota:"típica · nominal 7.290", cam:50,
    zoom:3, zoomTxt:"3x óptico (tele de 200 MP)", g5:true, loja:null, seg:null, dobra:null, foto:null,
    fonte:{url:"https://www.oppo.com/en/smartphones/series-find-x/find-x9-pro/specs/", acesso:"12/09/2026"}},
  ipair:{nome:"iPhone Air", curto:"iPhone Air", marca:"Apple", sigla:"AIR",
    alt:156.2, larg:74.7, esp:5.64, peso:165, tela:'6,5"', bateria:null, batNota:"Apple não declara mAh · até 27 h de vídeo", cam:48,
    zoom:0, zoomTxt:"sem teleobjetiva · 2x com qualidade óptica", g5:true, loja:"apple", seg:null, dobra:null,
    foto:{w:600, h:800, autor:"Ahmad Ali Karim", lic:"CC0", arquivo:"Sky_Blue_iPhone_Air.jpg", alt:"Traseira do iPhone Air, azul-céu."},
    fonte:{url:"https://www.apple.com/br/iphone-air/specs/", acesso:"12/09/2026"}}
};
